Repository AlokPatel99/Flappy-Bird-using-Neural-Network-and-Genetic-Algorithm, pull requests merged in 2020-11, with the labels that each got.

#1 Code base refactor + fix bugs + improve game
  Bird.py
  Game.py
  Pipe.py
  game_flappy.py
Labels: bug, enhancement

#3 Update NeuralNetwork.py
  NeuralNetwork.py
Labels: enhancement

#4 Add GA file
  GeneticAlgorithm.py
Labels: NewCode

#5 Update Game.py
  Game.py
Labels: enhancement

#6 Genetic algorithm
  .gitignore
  Bird.py
  Game.py
  GeneticAlgorithm.py
  NeuralNetwork.py
  Pipe.py
Labels: enhancement

#9 Update GeneticAlgorithm.py
  GeneticAlgorithm.py
Labels: enhancement

#15 Update Game.py
  Game.py
Labels: bug, enhancement

#16 Update GeneticAlgorithm.py
  GeneticAlgorithm.py
Labels: enhancement

#17 Expedite training
  Bird.py
  Game.py
  GeneticAlgorithm.py
  Images/slow-down.png
  Images/speed-up.png
  NeuralNetwork.py
  Pipe.py
Labels: bug, enhancement
